/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ClassementRouteImport } from './routes/classement'
import { Route as GestesRouteImport } from './routes/gestes'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as SimulateurRouteImport } from './routes/simulateur'
import { Route as AcademieIndexRouteImport } from './routes/academie/index'
import { Route as AcademieSportRouteImport } from './routes/academie/$sport'
import { Route as LeconLessonIdRouteImport } from './routes/lecon.$lessonId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassementRoute = ClassementRouteImport.update({
  id: '/classement',
  path: '/classement',
  getParentRoute: () => rootRouteImport,
} as any)
const GestesRoute = GestesRouteImport.update({
  id: '/gestes',
  path: '/gestes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulateurRoute = SimulateurRouteImport.update({
  id: '/simulateur',
  path: '/simulateur',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademieIndexRoute = AcademieIndexRouteImport.update({
  id: '/academie/',
  path: '/academie/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademieSportRoute = AcademieSportRouteImport.update({
  id: '/academie/$sport',
  path: '/academie/$sport',
  getParentRoute: () => rootRouteImport,
} as any)
const LeconLessonIdRoute = LeconLessonIdRouteImport.update({
  id: '/lecon/$lessonId',
  path: '/lecon/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/classement': typeof ClassementRoute
  '/gestes': typeof GestesRoute
  '/profil': typeof ProfilRoute
  '/simulateur': typeof SimulateurRoute
  '/academie/$sport': typeof AcademieSportRoute
  '/lecon/$lessonId': typeof LeconLessonIdRoute
  '/academie/': typeof AcademieIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/classement': typeof ClassementRoute
  '/gestes': typeof GestesRoute
  '/profil': typeof ProfilRoute
  '/simulateur': typeof SimulateurRoute
  '/academie/$sport': typeof AcademieSportRoute
  '/lecon/$lessonId': typeof LeconLessonIdRoute
  '/academie': typeof AcademieIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/classement': typeof ClassementRoute
  '/gestes': typeof GestesRoute
  '/profil': typeof ProfilRoute
  '/simulateur': typeof SimulateurRoute
  '/academie/$sport': typeof AcademieSportRoute
  '/lecon/$lessonId': typeof LeconLessonIdRoute
  '/academie/': typeof AcademieIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/classement'
    | '/gestes'
    | '/profil'
    | '/simulateur'
    | '/academie/$sport'
    | '/lecon/$lessonId'
    | '/academie/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/classement'
    | '/gestes'
    | '/profil'
    | '/simulateur'
    | '/academie/$sport'
    | '/lecon/$lessonId'
    | '/academie'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/classement'
    | '/gestes'
    | '/profil'
    | '/simulateur'
    | '/academie/$sport'
    | '/lecon/$lessonId'
    | '/academie/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ClassementRoute: typeof ClassementRoute
  GestesRoute: typeof GestesRoute
  ProfilRoute: typeof ProfilRoute
  SimulateurRoute: typeof SimulateurRoute
  AcademieSportRoute: typeof AcademieSportRoute
  LeconLessonIdRoute: typeof LeconLessonIdRoute
  AcademieIndexRoute: typeof AcademieIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classement': {
      id: '/classement'
      path: '/classement'
      fullPath: '/classement'
      preLoaderRoute: typeof ClassementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestes': {
      id: '/gestes'
      path: '/gestes'
      fullPath: '/gestes'
      preLoaderRoute: typeof GestesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulateur': {
      id: '/simulateur'
      path: '/simulateur'
      fullPath: '/simulateur'
      preLoaderRoute: typeof SimulateurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academie/': {
      id: '/academie/'
      path: '/academie'
      fullPath: '/academie/'
      preLoaderRoute: typeof AcademieIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academie/$sport': {
      id: '/academie/$sport'
      path: '/academie/$sport'
      fullPath: '/academie/$sport'
      preLoaderRoute: typeof AcademieSportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecon/$lessonId': {
      id: '/lecon/$lessonId'
      path: '/lecon/$lessonId'
      fullPath: '/lecon/$lessonId'
      preLoaderRoute: typeof LeconLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ClassementRoute: ClassementRoute,
  GestesRoute: GestesRoute,
  ProfilRoute: ProfilRoute,
  SimulateurRoute: SimulateurRoute,
  AcademieSportRoute: AcademieSportRoute,
  LeconLessonIdRoute: LeconLessonIdRoute,
  AcademieIndexRoute: AcademieIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
