/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AcademieIndexRouteImport } from './routes/academie/index'
import { Route as AcademieSportRouteImport } from './routes/academie/$sport'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademieIndexRoute = AcademieIndexRouteImport.update({
  id: '/academie/',
  path: '/academie/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademieSportRoute = AcademieSportRouteImport.update({
  id: '/academie/$sport',
  path: '/academie/$sport',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/academie/$sport': typeof AcademieSportRoute
  '/academie/': typeof AcademieIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/academie/$sport': typeof AcademieSportRoute
  '/academie': typeof AcademieIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/academie/$sport': typeof AcademieSportRoute
  '/academie/': typeof AcademieIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/academie/$sport' | '/academie/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/academie/$sport' | '/academie'
  id: '__root__' | '/' | '/auth' | '/academie/$sport' | '/academie/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  AcademieSportRoute: typeof AcademieSportRoute
  AcademieIndexRoute: typeof AcademieIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academie/': {
      id: '/academie/'
      path: '/academie'
      fullPath: '/academie/'
      preLoaderRoute: typeof AcademieIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academie/$sport': {
      id: '/academie/$sport'
      path: '/academie/$sport'
      fullPath: '/academie/$sport'
      preLoaderRoute: typeof AcademieSportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  AcademieSportRoute: AcademieSportRoute,
  AcademieIndexRoute: AcademieIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
