
do $g$
declare fb uuid; bk uuid; vb uuid;
begin
select id into fb from public.sports where slug='football';
select id into bk from public.sports where slug='basketball';
select id into vb from public.sports where slug='volleyball';

insert into public.gestures (sport_id,name,meaning,situation,sanction,restart,whistle,whistle_count,common_errors,federation,ruleset_version) values
(fb,'Coup franc direct','Bras tendu horizontalement dans la direction de l''équipe bénéficiaire.','Faute imprudente : tacle, poussée, main volontaire.','Coup franc direct, penalty si dans la surface.','Ballon arrêté, adversaires à 9,15 m.','Un coup de sifflet net et bref.',1,'Confondre avec le geste du coup franc indirect (bras levé).','IFAB','Lois du Jeu 2024/25'),
(fb,'Coup franc indirect','Bras levé verticalement, maintenu jusqu''à ce que le ballon soit touché par un autre joueur ou sorte du jeu.','Hors-jeu, jeu dangereux, gardien tenant le ballon trop longtemps.','Coup franc indirect.','Un but ne peut être marqué qu''après une seconde touche.','Un coup de sifflet bref.',1,'Baisser le bras trop tôt.','IFAB','Lois du Jeu 2024/25'),
(fb,'Penalty','Bras tendu et main pointée vers le point de penalty.','Faute passible d''un coup franc direct commise par un défenseur dans sa surface.','Penalty, éventuellement carton.','Tir depuis le point de penalty, joueurs hors surface et à 9,15 m.','Un coup de sifflet fort et long, puis un second pour autoriser le tir.',2,'Oublier le second coup de sifflet autorisant la frappe.','IFAB','Lois du Jeu 2024/25'),
(fb,'Avertissement (carton jaune)','Carton jaune brandi au-dessus de la tête vers le joueur fautif.','Comportement antisportif, contestation, retard à la reprise.','Avertissement.','Coup franc correspondant à la faute.','Un coup de sifflet pour arrêter le jeu.',1,'Montrer le carton sans identifier clairement le joueur.','IFAB','Lois du Jeu 2024/25'),
(fb,'Exclusion (carton rouge)','Carton rouge brandi au-dessus de la tête.','Faute grossière, violence, annihilation d''une occasion de but manifeste, second avertissement.','Exclusion, l''équipe joue en infériorité.','Coup franc ou penalty selon la faute.','Un coup de sifflet ferme.',1,'Sortir le rouge avant d''avoir maîtrisé la situation.','IFAB','Lois du Jeu 2024/25'),
(fb,'Avantage','Les deux bras tendus vers l''avant à hauteur de poitrine.','Une faute est commise mais l''équipe victime conserve une action prometteuse.','Aucune sanction immédiate ; carton possible au prochain arrêt.','Le jeu continue.','Pas de coup de sifflet.',0,'Siffler la faute alors que l''avantage était évident.','IFAB','Lois du Jeu 2024/25'),
(bk,'Faute personnelle','Poing fermé levé, puis désignation du numéro du joueur vers la table.','Contact illégal avec un adversaire.','Faute personnelle, lancers francs selon la situation.','Remise en jeu ou lancers francs.','Un coup de sifflet.',1,'Oublier d''annoncer le numéro et la sanction à la table.','FIBA','Règles officielles 2022'),
(bk,'Violation des 24 secondes','Rotation du poignet, main tapant l''épaule.','La possession dépasse 24 secondes sans tir valide.','Perte de balle.','Remise en jeu pour l''adversaire.','Un coup de sifflet.',1,'Siffler alors que le ballon a touché l''anneau.','FIBA','Règles officielles 2022'),
(bk,'Marcher','Rotation des poings l''un autour de l''autre devant la poitrine.','Le joueur déplace ses appuis illégalement sans dribbler.','Violation.','Remise en jeu pour l''adversaire.','Un coup de sifflet.',1,'Confondre avec la reprise de dribble.','FIBA','Règles officielles 2022'),
(bk,'Panier à 3 points','Trois doigts levés, puis les deux bras levés si le tir est réussi.','Tir réussi au-delà de la ligne des 3 points.','Aucune.','Remise en jeu par l''adversaire.','Pas de coup de sifflet.',0,'Signaler la tentative après le tir seulement.','FIBA','Règles officielles 2022'),
(vb,'Ballon dedans','Bras tendu vers le sol, main ouverte, doigts vers le terrain.','Le ballon touche à l''intérieur du terrain ou sur la ligne.','Point pour l''équipe attaquante.','Service de l''équipe qui marque.','Un coup de sifflet pour attribuer le point.',1,'Signaler avant que le ballon touche le sol.','FIVB','Règles 2021-2024'),
(vb,'Ballon dehors','Avant-bras levés verticalement, mains ouvertes, paumes vers soi.','Le ballon touche en dehors du terrain.','Point pour l''équipe adverse.','Service adverse.','Un coup de sifflet.',1,'Confondre avec le geste de quatre touches.','FIVB','Règles 2021-2024'),
(vb,'Faute de filet','Main posée sur la bande du filet du côté fautif.','Un joueur touche le filet pendant l''action de jouer le ballon.','Point pour l''adversaire.','Service adverse.','Un coup de sifflet.',1,'Sanctionner un contact hors antennes sans influence sur le jeu.','FIVB','Règles 2021-2024'),
(vb,'Quatre touches','Quatre doigts levés.','L''équipe a touché le ballon quatre fois avant de le renvoyer.','Point pour l''adversaire.','Service adverse.','Un coup de sifflet.',1,'Compter le contre comme une touche.','FIVB','Règles 2021-2024');

insert into public.scenarios (sport_id, level, difficulty, theme, situation, options, correct_index, explanation, wrong_explanations, federation, ruleset_version) values
(fb,'debutant',1,'Fautes','Un défenseur tacle un attaquant lancé vers le but, à l''extérieur de la surface. Le contact est net, sans intention de jouer le ballon, et l''attaquant était seul face au gardien.','["Rien","Coup franc direct seul","Coup franc direct + carton jaune","Coup franc direct + carton rouge"]'::jsonb,3,'Il s''agit de l''annihilation d''une occasion de but manifeste hors surface : coup franc direct et exclusion.','["Il y a bien faute, le contact est clair.","La sanction disciplinaire est obligatoire ici.","Le jaune ne suffit pas : l''occasion de but manifeste était réelle."]'::jsonb,'IFAB','Lois du Jeu 2024/25'),
(fb,'amateur',2,'Penalty','Dans sa surface, un défenseur tente un tacle et joue clairement le ballon en premier ; l''attaquant tombe ensuite sur sa jambe.','["Penalty","Jeu continue","Coup franc indirect","Penalty + jaune"]'::jsonb,1,'Le ballon est joué en premier de façon régulière : aucune faute, le jeu continue.','["Il n''y a pas faute, le ballon est joué en premier.","","Aucune faute technique n''a été commise.","Aucune faute donc aucune sanction disciplinaire."]'::jsonb,'IFAB','Lois du Jeu 2024/25'),
(fb,'amateur',2,'Hors-jeu','Sur un corner, un attaquant se trouve derrière tous les défenseurs et marque de la tête.','["But refusé pour hors-jeu","But valable","Coup franc indirect","Balle à terre"]'::jsonb,1,'Il n''y a jamais hors-jeu directement sur un corner : le but est valable.','["Le hors-jeu ne s''applique pas sur corner.","","Aucune infraction n''a été commise.","Aucune raison de reprendre par une balle à terre."]'::jsonb,'IFAB','Lois du Jeu 2024/25'),
(fb,'debutant',1,'Gardien','Un défenseur fait une passe volontaire du pied à son gardien, qui la saisit des mains dans sa surface.','["Penalty","Coup franc indirect dans la surface","Coup franc direct","Rien"]'::jsonb,1,'La passe en retrait du pied saisie à la main est sanctionnée d''un coup franc indirect à l''endroit de la faute.','["Ce n''est pas une faute passible d''un coup franc direct.","","Il s''agit d''une faute technique, donc indirect.","Il y a bien infraction."]'::jsonb,'IFAB','Lois du Jeu 2024/25'),
(bk,'debutant',1,'Chronomètres','Une équipe attaque depuis 23 secondes ; le tir touche l''anneau et un attaquant prend le rebond offensif.','["Violation des 24 s","Chrono remis à 14 s","Chrono remis à 24 s","Entre-deux"]'::jsonb,1,'Après un rebond offensif sur un tir ayant touché l''anneau, le chronomètre repart à 14 secondes.','["Le tir a touché l''anneau : pas de violation.","","La remise à 24 s ne s''applique qu''à une nouvelle possession adverse.","Aucune situation d''entre-deux ici."]'::jsonb,'FIBA','Règles officielles 2022'),
(bk,'amateur',2,'Fautes','Un joueur est victime d''une faute pendant son tir à 3 points réussi.','["Panier annulé","Panier + 1 lancer franc","3 lancers francs","Panier + 2 LF"]'::jsonb,1,'Le panier est accordé et le tireur bénéficie d''un lancer franc supplémentaire.','["La faute n''annule pas un panier réussi.","","Les 3 LF ne s''appliquent que si le tir est manqué.","Un seul lancer franc est accordé."]'::jsonb,'FIBA','Règles officielles 2022'),
(vb,'debutant',1,'Filet','Un attaquant frappe et son maillot effleure le filet entre les antennes pendant son geste.','["Point pour l''attaque","Faute de filet, point adverse","Rejeu","Avertissement"]'::jsonb,1,'Tout contact avec le filet entre les antennes pendant l''action de jouer le ballon est une faute.','["Le contact filet annule l''action.","","Il n''y a pas lieu de rejouer le point.","La sanction est un point, pas un avertissement."]'::jsonb,'FIVB','Règles 2021-2024'),
(vb,'amateur',2,'Touches','Le contre touche le ballon, puis l''équipe le joue trois fois avant de le renvoyer.','["Quatre touches, point adverse","Action régulière","Double touche","Rejeu"]'::jsonb,1,'Le contact au contre ne compte pas : l''équipe disposait bien de trois touches.','["Le contre n''est pas compté comme une touche.","","Aucune double touche n''est constatée.","Aucune raison de rejouer."]'::jsonb,'FIVB','Règles 2021-2024');
end $g$;
